# Generated by Django 3.0.3 on 2020-03-03 18:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=100)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=13)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('metodo', models.CharField(choices=[('EF', 'Efectivo'), ('TA', 'Tarjeta'), ('TR', 'Transferencia'), ('PA', 'Paypal'), ('CH', 'Cheque'), ('OT', 'Otro')], default='EF', max_length=2)),
                ('descripcion', models.TextField()),
                ('insercion', models.DateTimeField(default=datetime.datetime(2020, 3, 3, 18, 37, 38, 630399), editable=False)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
