# Generated by Django 3.0.3 on 2020-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20200305_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='fechahora',
            field=models.DateTimeField(),
        ),
    ]
